application: cfitlog
version: 01
runtime: python27
api_version: 1
threadsafe: true

handlers:
 - url: /css
   static_dir: css

 - url: /img
   static_dir: img
   
 - url: /js
   static_dir: js
    
 - url: /.*
   script: cfitlog.app

