application: cfitlog
version: a1
runtime: python27
api_version: 1
threadsafe: true

handlers:
 - url: /css
   static_dir: css

 - url: /img
   static_dir: img
   
 - url: /js
   static_dir: js
    
 - url: /.*
   script: cfitlog.app

libraries:
 - name: jinja2
   version:  2.6
